# Generated by Django 5.0.3 on 2024-09-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('job_type', models.CharField(max_length=100)),
                ('relation_with_insured', models.CharField(choices=[('none', '해당없음'), ('actual_employer', '실제사업주(동업자포함)'), ('sub_contractor', '하수급사업주')], max_length=50)),
                ('family_relation', models.CharField(choices=[('none', '해당없음'), ('spouse', '배우자'), ('parent', '부모'), ('child', '자녀'), ('sibling', '형제자매'), ('other_relative', '기타친인척')], max_length=50)),
                ('application_type', models.CharField(choices=[('work_accident', '업무상 사고'), ('work_disease', '업무상 질병'), ('commute_accident', '출퇴근 재해')], max_length=50)),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner_name', models.CharField(max_length=100)),
                ('business_management_number', models.CharField(max_length=50)),
                ('business_address', models.CharField(max_length=200)),
                ('accident_description', models.TextField()),
                ('checkbox_one', models.BooleanField(default=False)),
                ('checkbox_two', models.BooleanField(default=False)),
                ('checkbox_three', models.BooleanField(default=False)),
                ('witness_name', models.CharField(blank=True, max_length=100, null=True)),
                ('witness_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('witness_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('has_received_compensation', models.BooleanField(default=False, help_text='수령 여부')),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('receipt_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_source', models.CharField(blank=True, max_length=100, null=True)),
                ('attached_documents', models.ImageField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
