# Generated by Django 5.0.3 on 2024-09-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_injuryapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryapplication',
            name='accident_report',
            field=models.FileField(blank=True, null=True, upload_to='documents/accident_reports/'),
        ),
        migrations.AddField(
            model_name='injuryapplication',
            name='alien_registration',
            field=models.FileField(blank=True, null=True, upload_to='documents/alien_registrations/'),
        ),
        migrations.AddField(
            model_name='injuryapplication',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='documents/medical_reports/'),
        ),
        migrations.AddField(
            model_name='injuryapplication',
            name='wage_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/wage_statements/'),
        ),
        migrations.AddField(
            model_name='injuryapplication',
            name='witness_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/witness_statements/'),
        ),
    ]
