# Generated by Django 5.0.3 on 2024-09-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_injuryapplication_accident_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injuryapplication',
            name='accident_report',
        ),
        migrations.RemoveField(
            model_name='injuryapplication',
            name='alien_registration',
        ),
        migrations.RemoveField(
            model_name='injuryapplication',
            name='medical_report',
        ),
        migrations.RemoveField(
            model_name='injuryapplication',
            name='wage_statement',
        ),
        migrations.RemoveField(
            model_name='injuryapplication',
            name='witness_statement',
        ),
    ]
