# Generated by Django 5.0.3 on 2024-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_remove_injuryapplication_accident_confirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsubmission',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documentsubmission',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='accident_confirmation',
            field=models.ImageField(blank=True, null=True, upload_to='documents/accident_confirmations/'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='alien_registration',
            field=models.ImageField(blank=True, null=True, upload_to='documents/alien_registrations/'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='medical_report',
            field=models.ImageField(blank=True, null=True, upload_to='documents/medical_reports/'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='wage_statement',
            field=models.ImageField(blank=True, null=True, upload_to='documents/wage_statements/'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='witness_statement',
            field=models.ImageField(blank=True, null=True, upload_to='documents/witness_statements/'),
        ),
    ]
