# Generated by Django 5.0.3 on 2024-09-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_documentsubmission_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsubmission',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='accident_confirmation',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='alien_registration',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='medical_report',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='wage_statement',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='witness_statement',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
