# Generated by Django 5.0.3 on 2024-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_remove_documentsubmission_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='afterInjuryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('accident_date', models.DateField()),
                ('change_account', models.BooleanField(default=False, help_text='수령계좌를 변경하시겠습니까?')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('normal', '보통계좌'), ('protected', '보험급여 전용계좌(희망지킴이-압류금지계좌)')], max_length=50, null=True)),
                ('claim_start_date', models.DateField()),
                ('claim_end_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('employed', '취업함'), ('unemployed', '취업하지 못함')], max_length=50)),
                ('salary_received', models.BooleanField(default=False, help_text='청구 기간 중 급여를 받았습니까?')),
                ('received_compensation', models.BooleanField(default=False, help_text='동일한 사유로 보상을 받았습니까?')),
                ('compensation_receipt_date', models.DateField(blank=True, null=True)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compensation_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('compensation_documents', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('auto_payment_request', models.BooleanField(default=False, help_text='자동 지급 신청 여부')),
            ],
        ),
    ]
