# Generated by Django 5.0.3 on 2024-09-09 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_afterinjuryapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='afterDocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisabilityCompensation', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('Rehabilitation', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('VocationalTrainingSupport', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
